client:
  postman:
    meta_data:
      proxies: system
dir_rule:
  base_dir: E:\Projects\Python\iam57-onanibot\data\comics
  rule: Bd_Ptitle
download:
  cache: true
  image:
    decode: true
    suffix: .jpg
  threading:
    batch_count: 45
version: '2.0'
